### ISSUE TITLE
Feature Request - Available Update Check

### ISSUE THREAD

**Issue by rockatansky6** [khpylon/MachEWidget#2]
I would like to request adding the ability to check for, and possibly launch, app updates from within the app.

**Comment by khpylon** [comment]
I wanted to give you an update.  I thought this would be a really cool feature, even if there are only a few who might find it useful (being retired, I will never have two Mach-E's).  I've been working the past few days to rewrite the underlying code and have now have a working copy, but I don't have any way to really test with two vehicles since the data is keyed to the VIN.  I'm going to test for a day or so to make sure things still function as expected for a single vehicle, but if it's stable I'll push out over the weekend.

**Comment by khpylon** [comment]
The next release will have a feature which alerts you when a new update is available, but it was more complicated to add the ability to perform the update within the app so that won't be available yet.  I do plan to spend some more time looking into it, so I'll report back when after I look further into it.

**Comment by rockatansky6** [comment]
no worries. an alert would be great. i'm not the best at active monitoring for updates, and i'd hate to miss out on any enhancements you make.

i really do appreciate the work you've done. it's made being able to monitor my mach-e at a glace much easier.

**Comment by johnlolis** [comment]
Any thoughts on using F-Droid (https://f-droid.org/)? Might solve the update issue.

**Comment by khpylon** [comment]
I'd be fine with using F-Droid, but from looking on their site I didn't see any described process for submitting a project.  Do you have any leads for what I'd need to do?  Would you be willing to look into it?

**Comment by khpylon** [comment]
It took me a while to figure out how to do this, but it will be in the next release.  It doesn't update the app automatically but will download the new update hand off to the installer for you.

**Comment by khpylon** [comment]
I think I've taken this as far as possible, so going to close for now.  If someone discovers the trick to allow for unattended updates feel free to reopen and share the details with me.
