### ISSUE TITLE
Feature request : Inside cabin temperature 

### ISSUE THREAD

**Issue by Naren567** [khpylon/MachEWidget#51]
Can we see inside cabin temperature for Mach E.

**Comment by khpylon** [comment]
I'm hesitant to add this since it doesn't appear to be visible in the "coming soon*" public API, so once I switch over this feature would go away.  Also, from my observations the temp only appears valid while the ignition is on (and probably accessory mode, but haven't checked).  

Want to start a poll on the forums to see 1) who else would be interested and 2) fine that it might only be temporary?

**Comment by khpylon** [comment]
I'll add this in the next version.  You'll just have to tap on the alarm icon and it will display the temp in a toast message.

**Comment by Naren567** [comment]
Thank you,  appreciate your time..

**Comment by khpylon** [comment]
Committed in Version 2024.02.17-22.
